services:
  chatservice:
    image: chatservice
    build:
      context: .
      dockerfile: ChatService/Dockerfile
      environment:
        - DB_HOST=mysql_message
        - DB_PORT=3306
        - DB_NAME=message
        - DB_USER=root
        - DB_PASSWORD=root
      depends_on:
        - mysql_message


  mysql_message:
    image: mysql:8.0
    container_name: mysql_message
    environment:
      MYSQL_DATABASE: message
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - mysql-data_message:/var/lib/mysql
        
volumes:
  mysql-data_message:
    driver: local